config-version: 1.5

update-notification: true
debug: false

main-settings:
  # MINIMESSAGE Example: <red>Hello
  # LEGACY Example: &cHello
  parse_mode: "MINIMESSAGE" # MINIMESSAGE or LEGACY
  lang: ENGLISH # RUSSIAN or ENGLISH
  actionbar: true

region-settings:
  hide-global-region: false
  disabled-worlds:
    - test
  blacklist:
    - test