name: LightShowRegion
version: ${pluginVersion}
main: ru.kainlight.lightshowregion.Main
api-version: 1.17

authors: [ kainlight ]
description: ${description}
website: vk.com/kainlight

depend: [ WorldGuard ]
softdepend: [ PlaceholderAPI ]
loadbefore: [ WorldGuard, PlaceholderAPI ]

libraries:
  - net.kyori:adventure-api:${adventureVersion}
  - net.kyori:adventure-text-minimessage:${adventureVersion}
  - net.kyori:adventure-platform-bukkit:${adventureBukkitVersion}
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}

commands:
  lightshowregion:
    aliases:
      - lsr

permissions:
  lightshowregion.toggle:
    default: true
  lightshowregion.help:
    default: op
  lightshowregion.global:
    default: op
  lightshowregion.add:
    default: op
  lightshowregion.remove:
    default: op
  lightshowregion.blacklist.add:
    default: op
  lightshowregion.blacklist.remove:
    default: op
  lightshowregion.blacklist.*:
    default: op
    children:
      lightshowregion.blacklist.add: true
      lightshowregion.blacklist.remove: true
  lightshowregion.reload.config:
    default: op
  lightshowregion.reload.actionbar:
    default: op
  lightshowregion.reload.bossbar:
    default: op
  lightshowregion.reload.bars:
    default: op
  lightshowregion.reload.*:
    default: op
    children:
      lightshowregion.reload.config: true
      lightshowregion.reload.bars.*: true
  lightshowregion.*:
    default: op
    children:
      lightshowregion.toggle: true
      lightshowregion.help: true
      lightshowregion.global: true
      lightshowregion.add: true
      lightshowregion.remove: true
      lightshowregion.blacklist.*: true
      lightshowregion.reload.*: true